version: "3.7"
services:
  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./db:/db:delegated
    working_dir: /db
    command: /bin/sh -c "./start_db.sh"
    user: root

  frontend:
    build: ./frontend
    image: frontend
    volumes:
      - ./frontend:/frontend
      - ./.vscode-server:/root/.vscode-server
    working_dir: /frontend
    environment: 
      NODE_ENV: "development"
    command: npm start
    
  backend:
    build: ./backend
    image: backend
    volumes:
      - ./backend:/backend
      - ./db:/db:delegated
      - ./.vscode-server:/root/.vscode-server
    working_dir: /backend
    dns:
      - 8.8.8.8
    command: sleep infinity
    user: root
